INSERT INTO character (name, race, job, hp, background, npc_type) VALUES ('Beldrath', 'Half-Elf', 'Paladin', 125, 'Urban Bounty Hunter', 'Combat');
INSERT INTO character (name, race, job, hp, background, npc_type) VALUES ('Minthrad', 'Human', 'Arch-Wizard', 200, 'Sage', 'Patron');
INSERT INTO character (name, race, job, hp, background, npc_type) VALUES ('Minerva', 'Halfling', 'Tavern Hostess', 10, 'Outlander', 'Commoner');
INSERT INTO character (name, race, job, hp, background, npc_type) VALUES ('Terath', 'Half-Orc', 'Innkeeper', 10, 'Urchin', 'Commoner');
INSERT INTO character (name, race, job, hp, background, npc_type) VALUES ('Chard', 'Human', 'Shopkeeper', 10, 'Soldier', 'Commoner');
INSERT INTO character (name, race, job, hp, background, npc_type) VALUES ('Byorg', 'Human', 'Barbarian', 175, 'Outlander', 'Combat');
INSERT INTO character (name, race, job, hp, background, npc_type) VALUES ('Valerea', 'Elf', 'Sorceror', 50, 'Charlatan', 'Combat');
INSERT INTO character (name, race, job, hp, background, npc_type) VALUES ('Mordrand', 'Dwarf', 'Cleric', 125, 'Acolyte', 'Combat');
INSERT INTO character (name, race, job, hp, background, npc_type) VALUES ('Chauncey', 'Human', 'Mayor', 10, 'Noble', 'Nobility');
INSERT INTO character (name, race, job, hp, background, npc_type) VALUES ('Lord Farci', 'Human', 'Duke of Wellingshire', 10, 'Noble', 'Nobility');
INSERT INTO character (name, race, job, hp, background, npc_type) VALUES ('Vendril', 'Lich', 'Arch-Lich Wizard', 500, 'Demigod', 'Boss');
INSERT INTO character (name, race, job, hp, background, npc_type) VALUES ('Gnarthon', 'Ogre', 'Fighter', 160, 'Soldier', 'Boss');
INSERT INTO character (name, race, job, hp, background, npc_type) VALUES ('Reginald', 'Halfling', 'Rogue', 60, 'Harper Agent', 'Quest Contact');
INSERT INTO character (name, race, job, hp, background, npc_type) VALUES ('Calenor', 'Half-Elf', 'Cleric', 75, 'Acolyte', 'Quest Contact');
INSERT INTO character (name, race, job, hp, background, npc_type) VALUES ('Balgethron', 'Drow Elf', 'Wizard', 175, 'Red Wizard', 'Patron');